sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make
  - docker run -d --name consul-standalone ldejager/consul-standalone

script:
  - docker ps | grep -q consul-standalone
